stages:
  - run
  - build
  - doc

before_script:
  - python -V
  - pip -V
    
jstests:
  stage: run
  image: thebjorn/dknode2:latest
  script:
    - npm install -g jest
    - yarn
    - jest --coverage

py27_dj17:
  stage: run
  image: thebjorn/dktestpackage2:latest
  script:
    - dk testpackage --ci --tag=py27-dj17
  allow_failure: true
  artifacts:
    paths:
      - build/*

py27_dj18:
  stage: run
  image: thebjorn/dktestpackage2:latest
  script:
    - dk testpackage --ci --django=1.8.19 --tag=py27-dj18
  allow_failure: true
  artifacts:
    paths:
      - build/*

py37_dj17:
  stage: run
  image: thebjorn/dktestpackage3:latest
  script:
    - dk testpackage --ci --tag=py37-dj17
  allow_failure: true
  artifacts:
    paths:
      - build/*

py37_dj18:
  stage: run
  image: thebjorn/dktestpackage3:latest
  script:
    - dk testpackage --ci --django=1.8.19 --tag=py37-dj18
  allow_failure: true
  artifacts:
    paths:
      - build/*

coverage:
  stage: build
  image: thebjorn/dktestpackage2:latest
  script:
    - dk combine-coverage
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  dependencies:
    - py27_dj17
    - py27_dj18
    - py37_dj18
  artifacts:
    paths:
      - build/coverage/*

wheel:
  stage: build
  image: thebjorn/dktestpackage2:latest
  script:
    - dk build-wheel
  dependencies:
    - py27
  artifacts:
    paths:
      - docs/badge-wheel.rst

pages:
  stage: doc
  image: thebjorn/dktestpackage2:latest
  script:
    - dk build-docs
  dependencies:
    - coverage
    - wheel
  artifacts:
    paths:
      - public
  only:
    - master
