
include:
  - project: 'norsktest/dktools'
    file: '/ci-templates/dkbuild.yml'

    
jstests:
  stage: test
  image: thebjorn/dknode2:latest
  before_script:
    - node --version
    - npm --version
  script:
    - npm install -g codecov
    - npm install -g jest
    - yarn
    - jest --coverage
  after_script:
    - codecov

jsbuild:
  stage: build
  image: thebjorn/dknode2:latest
  variables:
    DKBUILD_TYPE: "PRODUCTION"
  script:
    - yarn
    - npx webpack
  # artifacts:
  #   - ...
  dependencies:
    - jstests    

py27dj18:
  extends: .testpackage
  script:
    - dk testpackage --ci --django=1.8.19 --tag=py27-dj18

py35dj18:
  extends: .testpackage
  image: thebjorn/dktestpackage3:latest
  script:
    - dk testpackage --ci --django=1.8.19 --tag=py35-dj18

coverage:
  dependencies:
    - py27dj18
    - py35dj18

wheel:
  dependencies:
    - py27dj18
