matrix:
  include:

    - language: node_js
      node_js:
        - "11"
#      cache:
#        yarn: true
#        directories:
#          - node_modules
      install:
        - npm install -g codecov
        - npm install -g jest
        - yarn
      script:
        - jest --coverage && codecov

    - language: python
      python: "2.7"
      install: pip install -r requirements.txt
      script: pytest -v --cov=dkjs tests
      after_success: codecov

    - language: python
      python: "3.6"
      install: pip install -r requirements.txt
      script: pytest -v --cov=dkjs tests
      after_success: codecov

    - language: python
      python: "3.7"
      dist: xenial
      sudo: true
      install: pip install -r requirements.txt
      script: pytest -v --cov=dkjs tests
      after_success: codecov

notifications: 
  email:
    - bp@datakortet.no
