nodeLinker: node-modules

npmScopes:
  norsktest:
    npmAuthToken: "${NPM_DEPLOY_TOKEN}"
    npmPublishRegistry: "https://gitlab.com/api/v4/projects/13965270/packages/npm/"
    npmRegistryServer: "https://gitlab.com/api/v4/packages/npm"
